### ISSUE TITLE
hi, DANCE on cifar-10 IPC=50 only get 75 acc,your paper are 76

### ISSUE THREAD

**Issue by Luo-Zhongwei** [Hansong-Zhang/DANCE#2]
how to solve that?thank you

**Comment by Hansong-Zhang** [comment]
> how to solve that?thank you

Hi zhongwei,
Can you provide your hyper-parameters so that i can check if there is any difference between yours and mine.
Besides, have you tried to change the random seeds?

Best,
Hansong
